<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extendedconfigurations" nsURI="http://www.etsi.org/spec/TDL/1.3.1/configurations"
    nsPrefix="configurations">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="tdl" value="tdl.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedTestConfiguration" eSuperTypes="tdl.ecore#//TestConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" ordered="false"
        upperBound="-1" eType="#//TestConfigurationInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" ordered="false"
        upperBound="-1" eType="#//TestConfigurationOperation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestConfigurationInstance" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="ecore:EClass tdl.ecore#//TestConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestConfigurationOperation" abstract="true"
      eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//ComponentReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentReference" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass tdl.ecore#//ComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//TestConfigurationInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentMerge" eSuperTypes="#//TestConfigurationOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ComponentReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentHide" eSuperTypes="#//TestConfigurationOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReassignRole" eSuperTypes="#//TestConfigurationOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" lowerBound="1" eType="ecore:EEnum tdl.ecore#//ComponentInstanceRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentAlias" eSuperTypes="#//TestConfigurationOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedGateReference" eSuperTypes="tdl.ecore#//GateReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//TestConfigurationInstance"/>
  </eClassifiers>
</ecore:EPackage>
