<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="structuredobjectives" nsURI="http://www.etsi.org/spec/TDL/1.3.1/structured"
    nsPrefix="structured">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="tdl" value="tdl.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredTestObjective" eSuperTypes="tdl.ecore#//TestObjective">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="ecore:EClass tdl.ecore#//TestConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialConditions" eType="#//InitialConditions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expectedBehaviour" eType="#//ExpectedBehaviour"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finalConditions" eType="#//FinalConditions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="picsReference" upperBound="-1"
        eType="#//PICSReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" eType="#//Variants"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialConditions" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
        eType="#//EventSequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventSequence" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" lowerBound="1"
        upperBound="-1" eType="#//EventOccurrence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventOccurrence" abstract="true" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeConstraint" eType="ecore:EClass tdl.ecore#//TimeConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeLabel" eType="ecore:EClass tdl.ecore#//TimeLabel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpectedBehaviour" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenClause" eType="#//EventSequence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenClause" lowerBound="1"
        eType="#//EventSequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalConditions" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
        eType="#//EventSequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PICSReference" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pics" lowerBound="1" eType="#//PICS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PICS" eSuperTypes="tdl.ecore#//PackageableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="tdl.ecore#//PackageableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="tdl.ecore#//PackageableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventOccurrenceSpecification" eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityReference" eType="#//EntityReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventReference" lowerBound="1"
        eType="#//EventReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oppositeEntityReference"
        upperBound="-1" eType="#//EntityReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventArgument" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityReference" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="ecore:EClass tdl.ecore#//ComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventReference" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" eSuperTypes="tdl.ecore#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventArgument" eSuperTypes="tdl.ecore#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataReference" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        eType="ecore:EClass tdl.ecore#//StaticDataUse" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false"
        upperBound="-1" eType="#//Content" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="ecore:EClass tdl.ecore#//Member"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false"
        upperBound="-1" eType="#//Content" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="ecore:EClass tdl.ecore#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentReference" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        eType="#//Content"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralValueReference" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        eType="#//LiteralValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepeatedEventSequence" eSuperTypes="#//EventSequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repetitions" eType="#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interval" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTemplateOccurrence" eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTemplate" lowerBound="1"
        eType="#//EventSpecificationTemplate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityBinding" ordered="false"
        upperBound="-1" eType="#//EntityBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="occurrenceArgument" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventSpecificationTemplate" eSuperTypes="tdl.ecore#//PackageableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventSpecification" lowerBound="1"
        eType="#//EventOccurrenceSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityBinding" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateEntity" lowerBound="1"
        eType="#//EntityReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="occurrenceEntity" lowerBound="1"
        eType="#//EntityReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variants" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//Variant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variant" eSuperTypes="tdl.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectiveURI" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="picsReference" upperBound="-1"
        eType="#//PICSReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//VariantBinding" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariantBinding" eSuperTypes="tdl.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" lowerBound="1"
        eType="#//Value" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
