<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DSLSpecificCoverageRule" nsURI="https://org.imt.tdl.coverage/DSLSpecificCoverageRule"
    nsPrefix="DSLSpecificCoverageRule">
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceCoverages" upperBound="-1"
        eType="#//ReferenceCoverageInference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerCoverages" upperBound="-1"
        eType="#//ContainerCoverageInference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOn" upperBound="-1"
        eType="#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreClassFromCoverage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceCoverageInference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="AssociationReference" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerCoverageInference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ContainerReference" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="#//NumCoveredContained"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumCoveredContained">
    <eLiterals name="ALL"/>
    <eLiterals name="ONE" value="1"/>
  </eClassifiers>
</ecore:EPackage>
